### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by declan-casey**
Added the backend team to the README

### CODE REVIEW

**Review by dvonpingel — CHANGES_REQUESTED** [review]
I didn't do anything on the backend, so before this gets merged make sure my name and info aren't tied to here!

**Review by apcatanzariti — APPROVED** [review]
Awesome thank you for putting this together! Should be good to go once changes are made

**Review by alex-wallander — APPROVED** [review]
Looks great

**Review by dvonpingel — APPROVED** [review]
Looks great!

**Pull request merged**
